"""Model Loader Module for AI Sentiment Intelligence (Stage 5).

Provides reusable, robust functions for loading trained machine learning models,
the fitted TF-IDF vectorizer, and dynamically determining the best model
from Stage 4 evaluation metadata.

All loaders include strict error validation and clear error messaging.
"""

import json
from pathlib import Path
from typing import Any, Dict, Optional, Tuple, Union
import joblib

# Import configuration constants with fallback
try:
    from config import (
        BEST_MODEL_JSON,
        LINEAR_SVM_FILE,
        LOGISTIC_REGRESSION_FILE,
        MODEL_PATH,
        NAIVE_BAYES_FILE,
        SUPPORTED_LABELS,
        TFIDF_VECTORIZER_FILE,
    )
except ImportError:
    try:
        from src.config import (
            BEST_MODEL_JSON,
            LINEAR_SVM_FILE,
            LOGISTIC_REGRESSION_FILE,
            MODEL_PATH,
            NAIVE_BAYES_FILE,
            SUPPORTED_LABELS,
            TFIDF_VECTORIZER_FILE,
        )
    except ImportError:
        MODEL_PATH = Path("models")
        LOGISTIC_REGRESSION_FILE = MODEL_PATH / "logistic_regression.pkl"
        NAIVE_BAYES_FILE = MODEL_PATH / "naive_bayes.pkl"
        LINEAR_SVM_FILE = MODEL_PATH / "linear_svm.pkl"
        TFIDF_VECTORIZER_FILE = MODEL_PATH / "tfidf_vectorizer.pkl"
        BEST_MODEL_JSON = Path("results/best_model.json")
        SUPPORTED_LABELS = ["Positive", "Negative", "Neutral"]


# Mapping of model names to artifact file paths
MODEL_NAME_TO_FILE = {
    "Logistic Regression": LOGISTIC_REGRESSION_FILE,
    "Multinomial Naive Bayes": NAIVE_BAYES_FILE,
    "Linear SVM": LINEAR_SVM_FILE,
}


def load_model(filepath: Union[Path, str]) -> Any:
    """Load a serialized scikit-learn model artifact using joblib.

    Args:
        filepath: Path to the model pickle file.

    Returns:
        Loaded model instance.

    Raises:
        FileNotFoundError: If the model file does not exist.
        RuntimeError: If model loading fails due to corruption.
    """
    target_path = Path(filepath)
    if not target_path.exists():
        raise FileNotFoundError(
            f"[ERROR] Model artifact not found at: '{target_path.resolve()}'. "
            "Please ensure model training (Stage 3) has been executed."
        )
    try:
        model = joblib.load(target_path)
        return model
    except Exception as e:
        raise RuntimeError(f"[ERROR] Failed to load model artifact at '{target_path.resolve()}': {e}")


def load_vectorizer(filepath: Optional[Union[Path, str]] = None) -> Any:
    """Load the serialized TF-IDF vectorizer artifact.

    Args:
        filepath: Path to the vectorizer pickle file. Defaults to TFIDF_VECTORIZER_FILE.

    Returns:
        Fitted TfidfVectorizer instance.

    Raises:
        FileNotFoundError: If vectorizer artifact is missing.
    """
    if filepath is None:
        filepath = TFIDF_VECTORIZER_FILE
    target_path = Path(filepath)

    if not target_path.exists():
        raise FileNotFoundError(
            f"[ERROR] TF-IDF vectorizer artifact not found at: '{target_path.resolve()}'. "
            "Please ensure feature engineering (Stage 3) has been executed."
        )
    try:
        vectorizer = joblib.load(target_path)
        return vectorizer
    except Exception as e:
        raise RuntimeError(f"[ERROR] Failed to load TF-IDF vectorizer at '{target_path.resolve()}': {e}")


def load_best_model_metadata(filepath: Optional[Union[Path, str]] = None) -> Dict[str, Any]:
    """Load best model selection metadata generated by Stage 4.

    Args:
        filepath: Path to best_model.json. Defaults to BEST_MODEL_JSON.

    Returns:
        Metadata dictionary containing 'model_name', 'f1_score', 'accuracy', etc.

    Raises:
        FileNotFoundError: If best_model.json does not exist.
    """
    if filepath is None:
        filepath = BEST_MODEL_JSON
    target_path = Path(filepath)

    if not target_path.exists():
        raise FileNotFoundError(
            f"[ERROR] Best model selection metadata not found at: '{target_path.resolve()}'. "
            "Please run Stage 4 evaluation (python run_stage4.py) first."
        )

    with open(target_path, "r", encoding="utf-8") as f:
        metadata = json.load(f)

    if "model_name" not in metadata:
        raise KeyError(f"[ERROR] Invalid metadata format in '{target_path.resolve()}': missing 'model_name' key.")

    return metadata


def load_best_model(
    best_model_json_path: Optional[Union[Path, str]] = None,
) -> Tuple[Any, str, Dict[str, Any]]:
    """Dynamically determine and load the best model based on Stage 4 evaluation results.

    DOES NOT hardcode the model selection.

    Args:
        best_model_json_path: Path to best_model.json.

    Returns:
        Tuple of (loaded_model, model_name, metadata_dict).
    """
    metadata = load_best_model_metadata(best_model_json_path)
    model_name = metadata["model_name"]

    if model_name not in MODEL_NAME_TO_FILE:
        raise ValueError(
            f"[ERROR] Unknown model name '{model_name}' found in best_model.json. "
            f"Expected one of: {list(MODEL_NAME_TO_FILE.keys())}"
        )

    artifact_path = MODEL_NAME_TO_FILE[model_name]
    model = load_model(artifact_path)
    return model, model_name, metadata


def validate_model_artifacts() -> Dict[str, Any]:
    """Validate all required Stage 3 and Stage 4 artifacts before running predictions.

    Returns:
        Validation status dictionary with 'valid' boolean and detailed report.
    """
    report: Dict[str, Any] = {
        "valid": True,
        "errors": [],
        "best_model_name": None,
        "vectorizer_vocab_size": 0,
        "model_classes": [],
    }

    # 1. Check best_model.json
    try:
        meta = load_best_model_metadata()
        report["best_model_name"] = meta["model_name"]
    except Exception as e:
        report["valid"] = False
        report["errors"].append(str(e))

    # 2. Check vectorizer
    try:
        vec = load_vectorizer()
        report["vectorizer_vocab_size"] = len(vec.get_feature_names_out())
    except Exception as e:
        report["valid"] = False
        report["errors"].append(str(e))

    # 3. Check best model loading
    if report["best_model_name"]:
        try:
            model, _, _ = load_best_model()
            if hasattr(model, "classes_"):
                report["model_classes"] = list(model.classes_)
        except Exception as e:
            report["valid"] = False
            report["errors"].append(str(e))

    return report


def load_model_by_name(model_name: str) -> Tuple[Any, Path]:
    """Load a trained model artifact by its display name.

    Args:
        model_name: One of 'Logistic Regression', 'Multinomial Naive Bayes', 'Linear SVM'.

    Returns:
        Tuple of (loaded_model, artifact_path).

    Raises:
        ValueError: If model_name is not recognized.
    """
    if model_name not in MODEL_NAME_TO_FILE:
        raise ValueError(
            f"[ERROR] Unknown model name '{model_name}'. "
            f"Expected one of: {list(MODEL_NAME_TO_FILE.keys())}"
        )
    artifact_path = MODEL_NAME_TO_FILE[model_name]
    model = load_model(artifact_path)
    return model, artifact_path
